package model;

public enum TileType {
    WALL, FOOD, EMPTY, PACMAN, GHOST_BLUE, GHOST_RED, GHOST_PINK, GHOST_ORANGE, POWERUP, CHERRY, SPEEDPOWER, FREEZEPOWER, DOUBLEPOINTSPOWER, INVINCIBILITYPOWER, LIFEPOWER
}
